### PR TITLE
Curl removal and updates for latest mina

### PR DESCRIPTION
**Pull request by trvsdnn**
- Removed curl in favor of JSON + Net::HTTP, like the rollbar gem's capistrano implementation
- Renamed `rollbar_environment` to `rollbar_env` to align with other mina env setting names (it's backwards compatible)
- Changed errors to only exit the block, not the entire mina run (exiting is a bit aggressive and could cause weird issues depending on where the notify is in a user's deploy flow)'
- Bumped mina dependency and relaxed it
- Bumped `.ruby-version`
- Removed unused dev test dependencies and files

### CODE REVIEW

**Comment by nickveys** [comment]
Thanks for the PR!  If you wouldn't mind, a few tweaks before I merge this:

- Are these changes incompatible with mina 1.0?  It doesn't seem like it. If not, we should just relax the dependency to `~> 1.0` from `~> 1.0.0` instead of forcing `~> 1.1`.
- We use the test/reporting/linting tools on all our projects, please don't remove them.

**Comment by trvsdnn** [comment]
They actually were incompatible before I removed the `:environment` dependency on the notify task, but that shouldn't be needed, so the changes should be compatible with `~ 1.0`.

I didn't see any tests and just assumed the dev dependencies and test files were part of a boilerplate gemspec or gem builder you'd used, but overlooked cleaning up the unused gems. I typically like to keep unused gems out of dev dependencies so I'm not eating up space on developer drives needlessly, but I get why you'd want it.

That being said, happy to add them back.

**Comment by nickveys** [comment]
Great, I'll try to get this merged and released tonight.  Thanks!

**Comment by trvsdnn** [comment]
Will send a new PR.

**Pull request closed without merging**
